services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 8087:8080
    networks:
      - firefly_iii
    depends_on:
      - db
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel-cash
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiZDBhMmM2MmM5NDAyODJiM2IyYTJhYWEzOTA4MDZhODgiLCJ0IjoiYzI1NzliYmItY2IwMC00MmMyLTk2ZmItNGJmNzcxYTBiYTRmIiwicyI6Ik1EbGxOVEkyTldFdE16Qm1NUzAwWm1Rd0xXRTNaak10T1RBMlltRm1NamhqWldJMCJ9
    networks:
      - firefly_iii
  db:
    image: postgres
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/postgresql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    networks:
      - firefly_iii
    depends_on:
      - app
  youteller-api:
    container_name: youteller-api
    env_file: ./youteller-api/.env
    volumes:
      - ./youteller-api:/opt/app/youteller-api
      - ./youteller-api/cursors:/opt/app/youteller-api/cursors
    networks:
      - firefly_iii
    build:
      context: .
      dockerfile: ./youteller-api/Dockerfile
    ports:
      - 8085:8000
    depends_on:
      - app
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge